' Gambas module file

Public Function inArray(value As String, arr As Array) As Boolean
  For i As Integer = 0 To (arr.Length - 1) Step 1
    If value = arr[i] Then 
      Return 1
    Endif
  Next 
  Return 0 
End


Public Function stackToArray(itemStack As Stack) As Array
  Dim StackLen As Integer = itemStack.Size
  Dim arrRes As New String[StackLen]
  
  For i As Integer = 0 To StackLen - 1 Step 1
    arrRes.Add(itemStack.Pop())
  Next
  
  Return arrRes
End



Public Function revert(itemArray As Array) As Array
  Dim StackLen As Integer = itemArray.Length
  Dim arrRes As New String[StackLen]
  
  For i As Integer = StackLen - 1 To 0 Step -1
    arrRes.Add(itemArray[i])
  Next
  
  Return arrRes
End



Public Sub appendArrayToStack(st As Stack, arr As Array) 
  
  For z As Integer = 0 To arr.Length - 1 Step 1
    st.Push(arr[z])
  Next
  
End


Public Function toString(arr As Array) As String
  Dim str As String = ""
  
  For Each item As String In arr
    str &= item
  Next
  
  Return str
End













